### ISSUE TITLE
成功，感谢

### ISSUE THREAD

**Issue by DandiWong** [X1a0He/StarUML-Translate#1]
<img width="1200" alt="image" src="https://github.com/X1a0He/StarUML-CrackedAndTranslate/assets/856023/97a06087-b518-4529-a1de-fe5d3c6d1ac2">

感谢大佬。
请贴个微信/支付宝二维码，赞助一杯咖啡，以示感谢。

**Comment by X1a0He** [comment]
不需要了，感谢使用
