### ISSUE TITLE
[REQ] Cracked BUT NO Translate

### ISSUE THREAD

**Issue by zzk597** [X1a0He/StarUML-Translate#3]
That's work! Hopefully a cracked but untranslated version will be uploaded at the same time.

**Comment by X1a0He** [comment]
Thank you very much for your use, I am glad to get your suggestions.

StarUML 6.2.2 cracked only asar is released.

Please go to the [Release page](https://github.com/X1a0He/StarUML-CrackedAndTranslate/releases/tag/6.2.2), download `app-only-cracked.asar`, rename it to `app.asar`, and replace the file under the corresponding system.

Thank you again for your use and support
