### ISSUE TITLE
运行 main.py 提示 PermissionError: [Errno 1] Operation not permitted。运行环境：asar V3.2.0、python3、npm10.8.2

### ISSUE THREAD

**Issue by yunxiangnian** [X1a0He/StarUML-Translate#4]
<img width="927" alt="image" src="https://github.com/user-attachments/assets/5f23e5a4-3c1b-48c0-8b07-b5ba8f62ce8d">

**Comment by X1a0He** [comment]
从图中可知你的设备是Mac，请使用如下命令
```bash
cd StarUML-CrackedAndTranslate
sudo python3 main.py
```

**Comment by HXavier21** [comment]
问题不仅仅在于脚本运行权限，还有运行main.py的应用的权限
如果在`Warp`、`VSCode`此类应用中运行，需在设置中授予此类应用相应权限
<img width="489" alt="image" src="https://github.com/user-attachments/assets/a73e914b-917a-4282-b863-b99154bd908b">
