### ISSUE TITLE
我替换文件后软件打不开了

### ISSUE THREAD

**Issue by marklzq2000113** [X1a0He/StarUML-Translate#8]

**Comment by X1a0He** [comment]
> 

请提供系统版本和报错提示

**Comment by klxiaoniu** [comment]
已经解决对Linux和Windows的兼容：https://github.com/X1a0He/StarUML-CrackedAndTranslate/pull/9

**Comment by marklzq2000113** [comment]
> > 
> 
> 请提供系统版本和报错提示
版本就是最新的6.3.0,换了app.asar后打开可以但是没有任何东西也使用不了任何功能

**Comment by X1a0He** [comment]
> > > 
> > 
> > 
> > 请提供系统版本和报错提示
> > 版本就是最新的6.3.0,换了app.asar后打开可以但是没有任何东西也使用不了任何功能

正在修复，是lib.so无法生成的问题，请稍后或明天重试

**Comment by X1a0He** [comment]
问题已修复 [6.3.0 Fixed](https://github.com/X1a0He/StarUML-CrackedAndTranslate/releases/tag/6.3.0)
